# Generated by Django 3.2.12 on 2022-04-05 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_timesheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='username',
            new_name='content',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='打刻日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='in_out',
            field=models.IntegerField(choices=[(1, 'IN'), (0, 'OUT')], default=None, verbose_name='IN/OUT'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='place',
            field=models.IntegerField(choices=[(1, '京町デイ'), (2, '日夏デイ'), (3, '甘呂デイ'), (4, 'ECC'), (5, 'わが家')], default=None, verbose_name='出勤場所名'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='スタッフ'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='time',
            field=models.TimeField(verbose_name='打刻時間'),
        ),
        migrations.AlterModelTable(
            name='timesheet',
            table='attendance',
        ),
    ]
