# Generated by Django 3.2.12 on 2022-04-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220406_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='content',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='start',
        ),
    ]
