# Generated by Django 3.2.12 on 2022-04-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220406_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyoumachidei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=200)),
                ('working_starttime', models.TimeField(default='00:00')),
                ('working_endtime', models.TimeField(default='00:00')),
                ('total_time', models.FloatField()),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
            ],
        ),
    ]
