# Generated by Django 3.2.12 on 2022-04-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_kyoumachidei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyoumachidei',
            name='breakfast',
            field=models.BooleanField(default=False, verbose_name='朝食'),
        ),
        migrations.AlterField(
            model_name='kyoumachidei',
            name='dinner',
            field=models.BooleanField(default=False, verbose_name='夕食'),
        ),
        migrations.AlterField(
            model_name='kyoumachidei',
            name='lunch',
            field=models.BooleanField(default=False, verbose_name='昼食'),
        ),
        migrations.AlterField(
            model_name='kyoumachidei',
            name='shift_name',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='kyoumachidei',
            name='total_time',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='合計時間'),
        ),
        migrations.AlterField(
            model_name='kyoumachidei',
            name='working_endtime',
            field=models.TimeField(default='00:00', verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='kyoumachidei',
            name='working_starttime',
            field=models.TimeField(default='00:00', verbose_name='開始時間'),
        ),
    ]
