# Generated by Django 3.2.12 on 2022-04-14 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_offices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Office_name',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.offices', verbose_name='事業所名'),
        ),
    ]
