# Generated by Django 3.2.12 on 2022-04-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_profile_office_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Office_name',
        ),
    ]
