# Generated by Django 3.2.12 on 2022-04-14 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_profile_office_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Office_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.offices'),
        ),
    ]
