# Generated by Django 3.2.12 on 2022-04-14 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_offices_office_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='offices',
            name='full_time',
            field=models.BooleanField(default=False, verbose_name='常勤'),
        ),
        migrations.AddField(
            model_name='offices',
            name='no_allowance_count',
            field=models.BooleanField(default=False, verbose_name='手当カウントしない'),
        ),
        migrations.AddField(
            model_name='offices',
            name='part_time',
            field=models.BooleanField(default=False, verbose_name='非常勤'),
        ),
        migrations.AddField(
            model_name='offices',
            name='time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='時間'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.offices', verbose_name='所属事務所'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='氏名'),
        ),
    ]
