# Generated by Django 3.2.12 on 2022-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20220414_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offices',
            name='full_time',
        ),
        migrations.RemoveField(
            model_name='offices',
            name='no_allowance_count',
        ),
        migrations.RemoveField(
            model_name='offices',
            name='part_time',
        ),
        migrations.RemoveField(
            model_name='offices',
            name='time',
        ),
        migrations.AddField(
            model_name='employee',
            name='full_time',
            field=models.BooleanField(default=False, verbose_name='常勤'),
        ),
        migrations.AddField(
            model_name='employee',
            name='no_allowance_count',
            field=models.BooleanField(default=False, verbose_name='手当カウントしない'),
        ),
        migrations.AddField(
            model_name='employee',
            name='part_time',
            field=models.BooleanField(default=False, verbose_name='非常勤'),
        ),
        migrations.AddField(
            model_name='employee',
            name='time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='時間'),
        ),
    ]
