# Generated by Django 3.2.12 on 2022-04-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20220414_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='office_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.offices', verbose_name='所属事務所'),
        ),
    ]
