# Generated by Django 3.2.12 on 2022-04-19 02:14

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_employee_office_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offices',
            name='id',
            field=models.CharField(default=blog.models.create_id, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
