# Generated by Django 3.2.12 on 2022-04-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_offices_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offices',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
