# Generated by Django 3.2.12 on 2022-04-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_kyoumachidei_office_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyoumachidei',
            name='office_id',
        ),
    ]
