# Generated by Django 3.2.12 on 2022-04-19 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_kyoumachidei_office_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyoumachidei',
            name='office_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.offices', verbose_name='事務所名'),
        ),
    ]
