# Generated by Django 3.2.12 on 2022-04-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_kyoumachidei_office_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyoumachidei',
            name='office_id_test',
            field=models.IntegerField(blank=True, choices=[(1, '京町デイ'), (2, '日夏デイ'), (3, '甘呂デイ'), (4, 'ECC')], default=None, null=True, verbose_name='事務所名'),
        ),
    ]
