# Generated by Django 3.2.12 on 2022-04-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_kyoumachidei_office_id_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyoumachidei',
            name='office_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='office_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.offices', verbose_name='所属事務所'),
        ),
    ]
