# Generated by Django 3.2.12 on 2022-04-19 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0025_auto_20220419_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='office_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.offices', verbose_name='所属事務所'),
        ),
        migrations.AlterField(
            model_name='offices',
            name='office_manager',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
