# Generated by Django 3.2.12 on 2022-04-21 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20220419_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyoumachidei',
            name='office_id_test_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.offices', verbose_name='事務所名2'),
        ),
    ]
