# Generated by Django 3.2.12 on 2022-04-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20220422_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyoumachidei',
            name='remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='備考欄'),
        ),
    ]
