# Generated by Django 3.2.12 on 2022-04-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_kyoumachidei_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyoumachidei',
            name='remarks',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='合計時間'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='備考欄'),
        ),
    ]
