# Generated by Django 3.2.12 on 2022-04-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20220423_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='office_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.offices', verbose_name='出勤事務所名'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='place',
            field=models.IntegerField(blank=True, choices=[(1, '京町デイ'), (2, '日夏デイ'), (3, '甘呂デイ'), (4, 'ECC'), (5, 'わが家')], default=None, null=True, verbose_name='出勤場所名'),
        ),
    ]
