# Generated by Django 3.2.12 on 2022-04-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20220423_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='attendance_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='出勤時間'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='leaving_work_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='退勤時間'),
        ),
    ]
