# Generated by Django 3.2.12 on 2022-04-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20220425_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='所属長'),
        ),
    ]
