# Generated by Django 3.2.12 on 2022-04-26 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0034_employee_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='place',
        ),
        migrations.AlterField(
            model_name='employee',
            name='office_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.offices', verbose_name='所属事業所'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='kyoumachidei',
            name='shift_name',
            field=models.CharField(max_length=200, verbose_name='シフト名'),
        ),
        migrations.AlterField(
            model_name='offices',
            name='office_manager',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属長'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='office_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.offices', verbose_name='事業所'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='shift_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.kyoumachidei', verbose_name='シフト選択'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
