# Generated by Django 3.2.12 on 2022-04-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20220426_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='in_out',
            new_name='henkou',
        ),
    ]
