# Generated by Django 3.2.12 on 2022-04-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_rename_in_out_timesheet_henkou'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='henkou',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='time',
        ),
    ]
