# Generated by Django 3.2.12 on 2022-04-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20220427_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='日付'),
        ),
    ]
