# Generated by Django 3.2.12 on 2022-05-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_timesheet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='breakfast',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='朝食'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='dinner',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='夕食'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='lunch',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='昼食'),
        ),
    ]
