# Generated by Django 3.2.12 on 2022-05-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20220501_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='lunch',
        ),
    ]
