# Generated by Django 3.2.12 on 2022-05-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20220501_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='is_breakfast',
            field=models.BooleanField(default=False, verbose_name='朝食'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='is_dinner',
            field=models.BooleanField(default=False, verbose_name='夕食'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='is_lunch',
            field=models.BooleanField(default=False, verbose_name='昼食'),
        ),
    ]
