# Generated by Django 3.2.12 on 2022-05-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20220501_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='total_working_hours',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='合計勤務時間'),
        ),
    ]
