# Generated by Django 3.2.12 on 2022-05-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_timesheet_remarks_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='general_affairs_entry_field',
            field=models.TextField(blank=True, default=None, max_length=400, null=True, verbose_name='総務記入欄'),
        ),
    ]
